### ISSUE TITLE
关于mbr中文件系统偏移地方

### ISSUE THREAD

**Issue by snowlord** [chobits/tinyos#4]
ksize是内核所需要的扇区数。8表示前8个扇区。
build.c中73中 fsoff = ((8 + ksize) + 1) / 2。这个文件系统偏移开始地方会不会覆盖内核的内容。不懂为什么要除以2.

**Comment by chobits** [comment]
* BLOCK_SIZE: 1024, minix文件系统由block组成，每个block大小为1024
* tinyos启动使用的磁盘镜像(disk.img)格式为: 前4KB预留bootloader(boot.bin)，4KB开始预留给kernel(kernel.bin)，kernel之后是文件系统

```
disk.img:

[--boot.bin--][--kernel.bin--][--align--]|[---- file system ---]
|--4KB     --|                           '--- 1KB对齐

[block:0 ~ 3 ][block: 4 ~ ............. ] [ block: fsoff ~ ... ]
```
* `fsoff`即为file system的起始block号
  * 实际上`fsoff=(sizeof(boot.bin)+sizeof(kernel.bin)+sizeof(align)) / BLOCK_SIZE`  
  * 由于之前ksize已经除以512（相当于ksize表示sector数目)，所以这里再除以2（即512*2 => BLOCK_SIZE)
  * 8表示boot.bin占用8个sector，即使 8*512 => 4KB

---
* MBR offset 508写入: kernel.bin占用的sector数目 `(sizeof(kernel.bin) + 511)/ 512`
  * 供bootloader使用，从ATA磁盘读取kernel.bin到内存，参考`boot/main.c: load_kernel() -> disk_readsect()`
* MBR offset 506写入: file system起始block号（minix文件系统) `(sizeof(boot.bin)+sizeof(kernel.bin)+sizeof(align)) / BLOCK_SIZE`
  * 供kernel使用，用于初始化文件系统，参考 `fs/minix/init.c: minix_fs_init()` 和 宏`MINIXFS_START`
---

* sector概念及其大小512参考[ATA PIO Mode](http://wiki.osdev.org/ATA_PIO_Mode)，读ATA磁盘需要使用此参数
* tinyos中使用ATA PIO Mode读磁盘逻辑参考：`boot/main.c: load_kernel() -> disk_readsect()`

**Comment by snowlord** [comment]
嗯，原来是按照minix的块大小。
按照disk.img这样存储，应该是简单，方便。
disk.img:

[--boot.bin--][--kernel.bin--][--align--]|[---- file system ---]

实际中，是不是可以把kernel.bin放到file system中。如果放到里面。boot.bin实现读取Minix文件系统代码是否会超过4k吗

**Comment by chobits** [comment]
> 实际中，是不是可以把kernel.bin放到file system中。

是可以的。考虑到简单性，我这里把minix文件系统代码实现在kernel.bin里了，所以这里boot.bin只负责加载kernel.bin，而kernel.bin是不包含在file system里面的。

BTW，linux kernel的内核镜像是包含在file system里，如果使用GRUB 2来做boot loader，GRUB 2可以识别file system
